# Generated by Django 2.1 on 2018-08-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180807_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='currentPos',
            field=models.CharField(choices=[('', 'Select an option'), ('student', 'Student'), ('job', 'Full Time Job'), ('learner', 'Full Time Learner'), ('preferNo', 'Prefer not to say'), ('other', 'Other')], max_length=100),
        ),
    ]
