# Generated by Django 2.1 on 2018-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180807_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='languageProficient',
            field=models.CharField(choices=[('C', 'C'), ('cplus', 'C++'), ('csharp', 'C#'), ('html', 'Html'), ('jscript', 'Javascript'), ('python', 'Python'), ('java', 'Java')], max_length=50),
        ),
    ]
