# Generated by Django 2.1 on 2018-08-07 18:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20180807_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='languageProficient',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('cplus', 'C++'), ('csharp', 'C#'), ('html', 'Html'), ('jscript', 'Javascript'), ('python', 'Python'), ('java', 'Java')], max_length=39),
        ),
    ]
