# Generated by Django 2.1 on 2018-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20180807_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
